name: Prepare release

on:
  push:
    branches:
      - master

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}
  # We do NOT want `cancel-in-progress` here since only one website job
  # should run at a time to avoid upload race conditions.

jobs:
  create_release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Upload release assets
        run: |
          ./tools/create_release.py ${{ github.repository }} ${{ secrets.GITHUB_TOKEN }}
      - name: Upload releases.json
        uses: actions/upload-pages-artifact@v4

  update_index:
    needs: create_release
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}releases.json
    steps:
      - name: Deploy releases.json
        id: deploy
        uses: actions/deploy-pages@v4

  # Ideally we should trigger Meson's CI to update the website, but unfortunately
  # it requires a Personal Access Token. Instead clone meson and do it ourself.
  # This job is copied from Meson's workflows.
  update_website:
    # the site builder reads releases.json, so update that first
    needs: update_index
    env:
      HAS_SSH_KEY: ${{ secrets.WEBSITE_PRIV_KEY != '' }}
    runs-on: ubuntu-latest
    steps:
      - name: Install package
        run: |
          sudo apt-get update
          sudo apt-get -y install python3-pip ninja-build libjson-glib-dev
          python3 -m pip install hotdoc chevron strictyaml
      - name: Setup SSH Keys and known_hosts
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "${{ secrets.WEBSITE_PRIV_KEY }}"
        if: env.HAS_SSH_KEY == 'true'
      - name: Build website
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git clone https://github.com/mesonbuild/meson.git
          cd meson/docs
          ../meson.py setup _build
          ninja -C _build
      - name: Update website
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          cd meson/docs
          ninja -C _build upload
        if: env.HAS_SSH_KEY == 'true'
