name: Prepare release

on:
  push:
    branches:
      - master

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install nasm for OpenSSL generator
        run: sudo apt-get install --no-install-recommends nasm
      - name: Upload release assets
        run: |
          git fetch --unshallow --tags
          ./tools/create_release.py ${{ github.repository }} ${{ secrets.GITHUB_TOKEN }}
  # Ideally we should trigger Meson's CI to update the website, but unfortunately
  # it requires a Personal Access Token. Instead clone meson and do it ourself.
  # This job is copied from Meson's workflows.
  update_website:
    env:
      HAS_SSH_KEY: ${{ secrets.WEBSITE_PRIV_KEY != '' }}
    runs-on: ubuntu-latest
    steps:
      - name: Install package
        run: |
          sudo apt-get -y install python3-pip ninja-build libjson-glib-dev
          pip install hotdoc chevron strictyaml
      - name: Setup SSH Keys and known_hosts
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "${{ secrets.WEBSITE_PRIV_KEY }}"
        if: env.HAS_SSH_KEY == 'true'
      - name: Build website
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git clone https://github.com/mesonbuild/meson.git
          cd meson/docs
          ../meson.py setup _build
          ninja -C _build
      - name: Update website
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          cd meson/docs
          ninja -C _build upload
        if: env.HAS_SSH_KEY == 'true'
